# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 697)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TabView = QtWidgets.QTabWidget(self.centralwidget)
        self.TabView.setTabPosition(QtWidgets.QTabWidget.North)
        self.TabView.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.TabView.setTabsClosable(False)
        self.TabView.setMovable(False)
        self.TabView.setTabBarAutoHide(False)
        self.TabView.setObjectName("TabView")
        self.tab_video = QtWidgets.QWidget()
        self.tab_video.setObjectName("tab_video")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_video)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inout_controls = QtWidgets.QHBoxLayout()
        self.inout_controls.setObjectName("inout_controls")
        self.lbl_infile = QtWidgets.QLabel(self.tab_video)
        self.lbl_infile.setObjectName("lbl_infile")
        self.inout_controls.addWidget(self.lbl_infile)
        self.lineedit_infile = QtWidgets.QLineEdit(self.tab_video)
        self.lineedit_infile.setObjectName("lineedit_infile")
        self.inout_controls.addWidget(self.lineedit_infile)
        self.btn_openin_video = QtWidgets.QPushButton(self.tab_video)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_openin_video.sizePolicy().hasHeightForWidth())
        self.btn_openin_video.setSizePolicy(sizePolicy)
        self.btn_openin_video.setMinimumSize(QtCore.QSize(30, 0))
        self.btn_openin_video.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_openin_video.setObjectName("btn_openin_video")
        self.inout_controls.addWidget(self.btn_openin_video)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.inout_controls.addItem(spacerItem)
        self.lbl_output = QtWidgets.QLabel(self.tab_video)
        self.lbl_output.setObjectName("lbl_output")
        self.inout_controls.addWidget(self.lbl_output)
        self.lineedit_output = QtWidgets.QLineEdit(self.tab_video)
        self.lineedit_output.setObjectName("lineedit_output")
        self.inout_controls.addWidget(self.lineedit_output)
        self.btn_chooseout_video = QtWidgets.QPushButton(self.tab_video)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_chooseout_video.sizePolicy().hasHeightForWidth())
        self.btn_chooseout_video.setSizePolicy(sizePolicy)
        self.btn_chooseout_video.setMinimumSize(QtCore.QSize(30, 0))
        self.btn_chooseout_video.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_chooseout_video.setObjectName("btn_chooseout_video")
        self.inout_controls.addWidget(self.btn_chooseout_video)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.inout_controls.addItem(spacerItem1)
        self.label_uid = QtWidgets.QLabel(self.tab_video)
        self.label_uid.setObjectName("label_uid")
        self.inout_controls.addWidget(self.label_uid)
        self.lineedi_uid = QtWidgets.QLineEdit(self.tab_video)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedi_uid.sizePolicy().hasHeightForWidth())
        self.lineedi_uid.setSizePolicy(sizePolicy)
        self.lineedi_uid.setInputMask("")
        self.lineedi_uid.setText("")
        self.lineedi_uid.setMaxLength(32767)
        self.lineedi_uid.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineedi_uid.setObjectName("lineedi_uid")
        self.inout_controls.addWidget(self.lineedi_uid)
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.inout_controls.addItem(spacerItem2)
        self.btn_run_ocr = QtWidgets.QPushButton(self.tab_video)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_run_ocr.setFont(font)
        self.btn_run_ocr.setFlat(False)
        self.btn_run_ocr.setObjectName("btn_run_ocr")
        self.inout_controls.addWidget(self.btn_run_ocr)
        self.verticalLayout.addLayout(self.inout_controls)
        self.playercontainer = QtWidgets.QWidget(self.tab_video)
        self.playercontainer.setMinimumSize(QtCore.QSize(0, 0))
        self.playercontainer.setObjectName("playercontainer")
        self.verticalLayout.addWidget(self.playercontainer)
        self.TabView.addTab(self.tab_video, "")
        self.tab_data = QtWidgets.QWidget()
        self.tab_data.setObjectName("tab_data")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_data)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.TabView.addTab(self.tab_data, "")
        self.verticalLayout_2.addWidget(self.TabView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.TabView.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_infile.setText(_translate("MainWindow", "Input File"))
        self.btn_openin_video.setText(_translate("MainWindow", "..."))
        self.lbl_output.setText(_translate("MainWindow", "Output Folder"))
        self.btn_chooseout_video.setText(_translate("MainWindow", "..."))
        self.label_uid.setText(_translate("MainWindow", "UID"))
        self.btn_run_ocr.setText(_translate("MainWindow", "Run"))
        self.TabView.setTabText(self.TabView.indexOf(self.tab_video), _translate("MainWindow", "Video"))
        self.TabView.setTabText(self.TabView.indexOf(self.tab_data), _translate("MainWindow", "Data"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

